### ISSUE TITLE
Add official OWASP swag

### ISSUE THREAD

**Issue by psiinon** [OWASP/owasp-swag#10]
Looks like it could be here:
https://www.owasp.org/index.php/Marketing/Resources#tab=WELCOME

We could either copy it across ourselves or just add a link.
I'm tempted to just add a link until we get someone from the OWASP foundation to state that they will be happy to keep this repo up to date with the latest graphics...

**Comment by jmarcil** [comment]
Finally got my access to this repo! I have some backlogged stuff for Defcon to upload, but after I jump on this.

Note that I've been the one curating the Marketing Resources on the wiki in the past years, so I should be able to sort out what was already made. 

Now for the new content, that I don't know. We haven't had any centralized content update since a while afaik. People are now contacting Hugo (official OWASP Graphic Designer) directly to grab content directly from him. I'll try to point people to this repo as we progress.

**Comment by jmarcil** [comment]
I think we should add the files directly; this repo is made for people who wants to quickly clone/download zip and have all the files in a folder. The foundation can still administer it if they want to put the latest content they have, but the community is driving it.

I'll still keep the link to the original wiki page, with an emphasis on brand usage guidelines. I also except the wiki to go in archive mode at some point with the new website coming up.
